[versions]

kotlin = "1.9.20-Beta2"
kotlVersion = "0.0.15"
ktprotoVersion = "0.0.1"
kotlinxSerialization = "1.5.0"
kotlinxCoroutines = "1.7.3"
ktor = "2.3.4"

[libraries]

koTL = { module = "me.y9san9.kotl:core", version.ref = "kotlVersion" }
koTL-serialization = { module = "me.y9san9.kotl:serialization", version.ref = "kotlVersion" }
ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }

# Gradle plugins
kotlinxSerializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
